version: '2'
services:
    todo-app:
        image: todo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://todo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=todo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    todo-mongodb:
        extends:
            file: mongodb.yml
            service: todo-mongodb
